### ISSUE TITLE
Transfer to personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/reviewer#13]
@raymondben et al :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by raymondben** [comment]
Hi @maelle - I'm happy for it to go to ropensci-archive, unless one of the other authors wants to grab it. Thanks

**Comment by maelle** [comment]
Thank you, I'll transfer it!
